---
title: "About"
---

## Education

<font size="4">**ScM Candidate in Biostatistics**</font><br>Johns Hopkins School of Public Health | August 2025 - Present

<font size="4">**BA in Statistics**</font> with minors in Data Science and Global Health Studies<br>Northwestern University | September 2021 - June 2025

## Experience

<font size="4">**Korea Disease Control and Prevention**</font> | <a href="https://pure.ewha.ac.kr/en/persons/minah-park"><span style="color:  #515897;"> Health Convergence @ Ewha (Dr. Minah Park)</span></a> | <span style="color:  #495057;">Epidemiology Researcher</span></a> |  September 2024 - December 2024

<font size="4">**University of California, Los Angeles**</font> | <a href="https://www.hspp.ucla.edu/"><span style="color:  #515897;"> W Lab @ School of Dentistry (Dr. David Wong)</span></a> | <span style="color:  #495057;">Bioinformatics Researcher (NSF REU)</span></a> | June 2024 - August 2024

<font size="4">**Pfizer**</font> | Oncology & Rare Diseases, R&D</span></a> | <span style="color:  #495057;">Associate Data Manager, Clinical Data Sciences (NSF REU)</span></a> | June 2023 - August 2023

## Projects

<a href="https://github.com/louiseoh18/cfDNA-gastric-NGS.git"><span style="color: #000000;"> **Saliva cell-free DNA as a biomarker for early detection of gastric cancer**</span></a> Oh, L., Sarwar, H., et al. (2024). W Lab @ UCLA School of Dentistry.

<a href="https://github.com/louiseoh18/disease-trend-dashboard.git"><span style="color: #000000;"> **Dashboard: Communicable Disease Trends in OECD Countries**</span></a> by Louise Oh. (2023). Northwestern University (Data Science independent project)

<a href="https://github.com/louiseoh18/automobile-safety-ML.git"><span style="color: #000000;"> **Predicting Automobile Safety using ML**</span></a> by Louise Oh, Eileen Kwon, and Lucia Koo. (2024). Northwestern University (Data Science group project)

<a href="https://github.com/louiseoh18/pregnancy-care-ML.git"><span style="color: #000000;"> **Improving Pregnancy Care During the Pandemic**</span></a> by Louise Oh. (2024). Northwestern University (Data Science independent project)


## Personal

- I was born in New Jersey and raised in the Philippines and South Korea. 

- I enjoy lifting things overhead. Outside of classes, you can usually find me training for Olympic weightlifting. Every now and then, I’m forced to join CrossFit classes to get just enough cardio to survive everyday life. I also compete occasionally for fun.

- I used to play the piano with hopes of attending a conservatory, but eventually realized my greater passion lay elsewhere. Still, I love listening to orchestras and recitals, and I was especially excited to join an institution with a renowned music school like Peabody.
